apiVersion: v1
kind: Pod
metadata:
  labels:
    name: terraform
spec:
  volumes:
    - name: aws-creds
      secret:
        secretName: aws-creds
  containers:
    - name: terraform
      image: hashicorp/terraform:0.12.21
      command:
        - cat
      tty: true
      volumeMounts:
        - name: aws-creds
          mountPath: ~/.aws/credentials
      env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: ~/.aws/credentials
      resources:
        limits:
          memory: "512Mi"
          cpu: "350m"